[general]
import = [
    "~/.config/alacritty/themes/dark.toml"
]

live_config_reload = true

[font]
# Divide value by 0.75 for actual font size
size = 14.25

normal      = {family = "Hack Nerd Font Mono", style = "Regular"}
italic      = {family = "Hack Nerd Font Mono", style = "Italic"}
bold        = {family = "Hack Nerd Font Mono", style = "Bold"}
bold_italic = {family = "Hack Nerd Font Mono", style = "Bold Italic"}

[terminal.shell]
args    = ["bash", "-c", "source ~/.bash_profile && tmux -2 new-session -A -s main"]
program = "/usr/bin/env"

[env]
TERM = "xterm-256color"

[window]
padding       = {x = 4, y = 4}
decorations   = "none"
option_as_alt = "OnlyLeft"
