[general]
import = [
    "~/.config/alacritty/themes/carbonfox.toml"
]

live_config_reload = true

[font]
size = 14

normal      = {family = "MesloLGM Nerd Font Mono", style = "Regular"}
italic      = {family = "MesloLGM Nerd Font Mono", style = "Italic"}
bold        = {family = "MesloLGM Nerd Font Mono", style = "Bold"}
bold_italic = {family = "MesloLGM Nerd Font Mono", style = "Italic"}

[terminal.shell]
args    = ["bash", "-c", "source ~/.bash_profile && tmux -2 new-session -A -s main"]
program = "/usr/bin/env"

[env]
TERM = "xterm-256color"

[window]
padding       = {x = 4, y = 4}
decorations   = "none"
option_as_alt = "OnlyLeft"
