[general]
import = [
    "~/.config/alacritty/themes/terafox.toml"
]

live_config_reload = true

[font]
size = 14

normal      = {family = "DejaVuSansM Nerd Font Mono", style = "Regular"}
italic      = {family = "DejaVuSansM Nerd Font Mono", style = "Oblique"}
bold        = {family = "DejaVuSansM Nerd Font Mono", style = "Bold"}
bold_italic = {family = "DejaVuSansM Nerd Font Mono", style = "Bold Oblique"}

[terminal.shell]
args    = ["bash", "-c", "source ~/.profile && tmux -2 new-session -A -s main"]
program = "/usr/bin/env"

[env]
TERM = "xterm-256color"

[window]
padding       = {x = 4, y = 4}
decorations   = "none"
option_as_alt = "OnlyLeft"
