[general]
import = [
    "~/.config/alacritty/gruvbox-material-dark.toml"
]

live_config_reload = true

[font]
size = 18

[font.bold]
family = "D2CodingLigature Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "D2CodingLigature Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "D2CodingLigature Nerd Font Mono"
style = "Italic"

[font.normal]
family = "D2CodingLigature Nerd Font Mono"
style = "Regular"

[terminal.shell]
args = ["bash", "-c", "source ~/.profile && tmux -2 new-session -A -s main"]
program = "/usr/bin/env"

[env]
TERM = "xterm-256color"

[window.padding]
x = 3
y = 3

[window]
decorations = "none"
option_as_alt = "OnlyLeft"
