---
de_pkgs: [sway, rofi, waybar, redshift, wlsunset, alacritty, pavucontrol, thunar, wl-clipboard, grimshot]
gui_pkgs: [md.obsidian.Obsidian, org.onlyoffice.desktopeditors, grim-shot]
docker_pkgs: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin, docker-buildx-plugin]
os_pkgs: [flatpak]
python_build_deps:
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - curl
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev

font_dir: "{{ ansible_env['HOME'] }}/.local/share/fonts"

# Linux Specific Vars
pkg_repos_signing_keys:
  /usr/share/keyrings/hashicorp.asc: https://apt.releases.hashicorp.com/gpg
  /usr/share/keyrings/docker.asc: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"

pkg_repos:
  hashicorp: "deb [signed-by=/usr/share/keyrings/hashicorp.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
  docker: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/{{ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
