---
docker_pkgs:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
  - docker-buildx-plugin

repositories: [pyenv/pyenv, tfutils/tfenv]
common_pkgs: [vim, htop, tmux, jq, fzf, fzy, ripgrep]
os_pkgs: []
font_dir: "{{ ansible_env['HOME'] }}/.fonts"
fonts:
  Iosevka: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Iosevka.tar.xz
de_pkgs: [i3, rofi, polybar, feh, redshift, redshift-gtk]
