---
cli_pkgs: [vim, htop, tmux, jq, fzf, fzy, ripgrep, ranger, shellcheck]
de_pkgs: []
gui_pkgs: []
docker_pkgs: []
os_pkgs: []
python_build_deps: []

repositories: [pyenv/pyenv, tfutils/tfenv]

font_dir: ""
fonts:
  Iosevka: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Iosevka.tar.xz
  UbuntuMono: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/UbuntuMono.tar.xz
  Meslo: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Meslo.tar.xz

# MacOS Specific Vars
homebrew_casks: []

# Linux Specific Vars
pkg_repos_signing_keys: {}
pkg_repos: {}
