---
repositories:
  [
    {
      src: git@github.com:pyenv/pyenv.git,
      dest: "{{ ansible_env['HOME'] }}/Repos/tools/pyenv",
    },
    {
      src: git@github.com:tfutils/tfenv.git,
      dest: "{{ ansible_env['HOME'] }}/Repos/tools/tfenv",
    },
    {
      src: git@github.com:vim-python/python-syntax.git,
      dest: "{{ ansible_env['HOME'] }}/.vim/pack/plugins/start/python-syntax",
    },
    {
      src: git@github.com:tomasiser/vim-code-dark.git,
      dest: "{{ ansible_env['HOME'] }}/.vim/pack/themes/start/codedark",
    },
  ]
docker_pkgs:
  [
    docker-ce,
    docker-ce-cli,
    containerd.io,
    docker-compose-plugin,
    docker-buildx-plugin,
  ]
common_pkgs: [vim, htop, tmux, jq]
os_pkgs: [code]
virtualisation_pkgs: [virtualbox-7.0, vagrant]