---
- name: Retrieve GPG Keys For Package Repositories
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ pkg_repos_keys }}"

- name: Add Package Repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.filename }}"
    state: present
  become: true
  loop: "{{ pkg_repos }}"

- name: Update Apt Cache & Packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    autoremove: true
    update_cache: true
  become: true

- name: Install Standard Packages
  ansible.builtin.apt:
    name: "{{ common_pkgs + os_pkgs }}"
    state: present
  become: true

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ docker_pkgs }}"
    state: present
  become: true

- name: Enable Docker
  ansible.builtin.systemd:
    name: docker
    state: started
  become: true

- name: "Add '{{ ansible_user_id }}' To Docker Group"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  become: true

- name: Install Virtualisation Packages
  ansible.builtin.apt:
    name: "{{ virtualisation_pkgs }}"
    state: present
  when: ansible_facts['virtualization_role'] != 'guest'
